"""
Data models for the Research Report Processor.

This module defines all Pydantic models and enums used throughout the application,
as well as utility functions for generating unique IDs.
"""

import uuid
from datetime import datetime
from enum import Enum

from pydantic import BaseModel, Field


def generate_data_id() -> str:
    """
    Generate a unique Data_ID for each uploaded file.
    
    Uses UUID4 to ensure uniqueness across all files.
    
    Returns:
        str: A unique data ID in the format "data-{uuid4}"
    
    Validates: Requirement 1.6 - WHEN files are uploaded successfully, 
    THE Report_Processor SHALL generate a unique Data_ID for each file
    """
    return f"data-{uuid.uuid4().hex}"


def generate_task_id() -> str:
    """
    Generate a unique Task_ID for each processing task.
    
    Uses UUID4 to ensure uniqueness across all tasks.
    
    Returns:
        str: A unique task ID in the format "task-{uuid4}"
    
    Validates: Requirement 8.1 - WHEN a task is created, 
    THE Progress_Tracker SHALL assign a unique task ID and return it to the frontend
    """
    return f"task-{uuid.uuid4().hex}"


class TaskStage(str, Enum):
    """
    Enum representing the different stages of task processing.
    
    The task progresses through these stages sequentially:
    UPLOADING -> PARSING -> DOWNLOADING -> TRANSLATING -> SUMMARIZING -> GENERATING -> COMPLETED
    
    FAILED can occur at any stage if an error is encountered.
    """
    UPLOADING = "uploading"           # 上传到 MinerU
    PARSING = "parsing"               # MinerU 解析中
    DOWNLOADING = "downloading"       # 下载解析结果
    TRANSLATING = "translating"       # AI 翻译中
    SUMMARIZING = "summarizing"       # AI 总结中
    GENERATING = "generating"         # 生成输出文件
    COMPLETED = "completed"           # 完成
    FAILED = "failed"                 # 失败


class MineruTaskState(str, Enum):
    """
    Enum representing the MinerU task states as returned by the MinerU API.
    
    These states are used to track the progress of PDF parsing on MinerU's side.
    """
    WAITING_FILE = "waiting-file"     # 等待文件上传
    PENDING = "pending"               # 排队中
    RUNNING = "running"               # 解析中
    CONVERTING = "converting"         # 格式转换中
    DONE = "done"                     # 完成
    FAILED = "failed"                 # 失败


class OutputFileType(str, Enum):
    """
    Enum representing the different types of output files generated by the system.
    """
    ORIGINAL_MD = "original_md"       # 原文 Markdown
    ORIGINAL_DOCX = "original_docx"   # 原文 DOCX
    BILINGUAL_MD = "bilingual_md"     # 双语对照 Markdown
    BILINGUAL_DOCX = "bilingual_docx" # 双语对照 DOCX
    SUMMARY = "summary"               # 双语总结


class FileInfo(BaseModel):
    """
    Model representing information about an uploaded file.
    
    Attributes:
        name: The original filename
        data_id: Unique business data ID for the file (Requirement 1.6)
        size: File size in bytes
    """
    name: str                         # 文件名
    data_id: str                      # 业务数据 ID
    size: int                         # 文件大小（字节）


class BatchUploadResponse(BaseModel):
    """
    Model representing the response from MinerU batch upload API.
    
    Attributes:
        batch_id: The batch task ID returned by MinerU
        file_urls: List of pre-signed URLs for uploading files
    """
    batch_id: str                     # 批量任务 ID
    file_urls: list[str]              # 上传 URL 列表


class FileParseResult(BaseModel):
    """
    Model representing the parsing result for a single file from MinerU.
    
    Attributes:
        file_name: The original filename
        data_id: Business data ID (may be None if not yet assigned)
        state: Current parsing state
        full_zip_url: URL to download the result ZIP (available when done)
        err_msg: Error message if parsing failed
        extracted_pages: Number of pages already parsed
        total_pages: Total number of pages in the document
    """
    file_name: str                    # 文件名
    data_id: str | None = None        # 业务数据 ID
    state: MineruTaskState            # 解析状态
    full_zip_url: str | None = None   # 结果下载链接
    err_msg: str | None = None        # 错误信息
    extracted_pages: int | None = None  # 已解析页数
    total_pages: int | None = None    # 总页数


class BatchResultResponse(BaseModel):
    """
    Model representing the batch results response from MinerU API.
    
    Attributes:
        batch_id: The batch task ID
        extract_result: List of parsing results for each file in the batch
    """
    batch_id: str                     # 批量任务 ID
    extract_result: list[FileParseResult]  # 各文件解析结果


class ProgressUpdate(BaseModel):
    """
    Model representing a progress update for a task.
    
    This is used to broadcast progress updates via WebSocket.
    
    Attributes:
        task_id: The unique task ID (Requirement 8.1)
        stage: Current processing stage
        progress: Current progress count
        total: Total count for the current stage
        percentage: Overall progress percentage (0-100)
        message: Human-readable status message
        timestamp: When this update was generated
    """
    task_id: str                      # 任务 ID
    stage: TaskStage                  # 当前阶段
    progress: int                     # 当前进度
    total: int                        # 总数
    percentage: float                 # 总体进度百分比
    message: str                      # 状态消息
    timestamp: datetime = Field(default_factory=datetime.now)  # 时间戳


class TaskStatus(BaseModel):
    """
    Model representing the complete status of a processing task.
    
    Attributes:
        task_id: The unique task ID (Requirement 8.1)
        stage: Current processing stage
        files: List of files being processed
        progress: Current progress update
        outputs: Mapping of output file types to their paths (when complete)
        error: Error message if the task failed
        created_at: When the task was created
        updated_at: When the task was last updated
    """
    task_id: str                      # 任务 ID
    stage: TaskStage                  # 当前阶段
    files: list[FileInfo]             # 文件列表
    progress: ProgressUpdate          # 当前进度
    outputs: dict[str, str] | None = None  # 输出文件路径映射
    error: str | None = None          # 错误信息
    created_at: datetime = Field(default_factory=datetime.now)  # 创建时间
    updated_at: datetime = Field(default_factory=datetime.now)  # 更新时间


class ExtractedFiles(BaseModel):
    """
    Model representing files extracted from a MinerU result ZIP.
    
    Attributes:
        markdown_path: Path to the extracted Markdown file
        docx_path: Path to the extracted DOCX file (may be None)
        images: List of paths to extracted image files
    """
    markdown_path: str                # 提取的 Markdown 文件路径
    docx_path: str | None = None      # 提取的 DOCX 文件路径
    images: list[str] = Field(default_factory=list)  # 图片文件路径列表
